version: "3.8"

services:
  postgresdb:
    build:
      context: .
      target: db
    environment:
      - POSTGRES_USER=bunny
      - POSTGRES_PASSWORD=best_to_use_secrets
      - POSTGRES_DB=sampledb
    ports:
      - 5432:5432