version: "3.8"

services:
  postgresdb:
    image: postgresdb
    container_name: postgresdb
    build:
      context: .
      target: postgresdb
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sampledb
    ports:
      - 5432:5432